#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
- name: rw-rsc-counter
  type: web

  runtime: docker
  dockerfilePath: ./Dockerfile

  plan: free
  region: oregon
