#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
- name: rw-rsc-counter-web
  type: web

  runtime: docker
  dockerfilePath: ./Dockerfile.web

  plan: free
  region: oregon

# - name: rw-rsc-counter-api
#   type: web

#   runtime: docker
#   dockerfilePath: ./Dockerfile.api

#   plan: free
#   region: oregon

#   envVars:
#   - key: DATABASE_URL
#     fromDatabase:
#       name: rw-rsc-counter-db
#       property: connectionString

# databases:
#   - name: rw-rsc-counter-db
#     region: oregon
